default_agent: bedrock_manus_runtime
agents:
  bedrock_manus_runtime:
    name: bedrock_manus_runtime
    entrypoint: /home/ubuntu/aws-ai-ml-workshop-kr/genai/aws-gen-ai-kr/20_applications/08_bedrock_manus/use_cases/05_insight_extractor_strands_sdk_workshop_phase_2/agentcore_runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::057716757052:role/agentcore-bedrock_manus_runtime-role
      execution_role_auto_create: false
      account: '057716757052'
      region: us-east-1
      ecr_repository: 057716757052.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-bedrock_manus_runtime
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: bedrock_manus_runtime-E8I6oFGlTA
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:057716757052:runtime/bedrock_manus_runtime-E8I6oFGlTA
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-bedrock_manus_runtime-builder
      execution_role: arn:aws:iam::057716757052:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-b015ee5cd0
      source_bucket: bedrock-agentcore-codebuild-sources-057716757052-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
