default_agent: customer_support_agent
agents:
  customer_support_agent:
    name: customer_support_agent
    entrypoint: /home/ubuntu/Self-Study-Generative-AI/lab/17_bedrock_agent_core/01-tutorials/07-AgentCore-E2E/lab_helpers/lab4_runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::057716757052:role/CustomerSupportAssistantBedrockAgentCoreRole-us-east-1
      execution_role_auto_create: false
      account: '057716757052'
      region: us-east-1
      ecr_repository: 057716757052.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-customer_support_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: customer_support_agent-fh7PV65rcr
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:057716757052:runtime/customer_support_agent-fh7PV65rcr
      agent_session_id: d59005b7-5afd-4709-835e-ade72baac054
    codebuild:
      project_name: bedrock-agentcore-customer_support_agent-builder
      execution_role: arn:aws:iam::057716757052:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-aa96c3a063
      source_bucket: bedrock-agentcore-codebuild-sources-057716757052-us-east-1
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 6alrcnckui47t036qvon48p4a0
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_8eROuquri/.well-known/openid-configuration
    oauth_configuration: null
