default_agent: deep_insight_runtime_vpc
agents:
  deep_insight_runtime_vpc:
    name: deep_insight_runtime_vpc
    entrypoint: /home/ubuntu/aws-ai-ml-workshop-kr/genai/aws-gen-ai-kr/20_applications/08_bedrock_manus/use_cases/05_insight_extractor_strands_sdk_workshop_phase_2/agentcore_runtime.py
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::057716757052:role/agentcore-bedrock_manus_runtime-role
      execution_role_auto_create: false
      account: '057716757052'
      region: us-east-1
      ecr_repository: 057716757052.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-deep_insight_runtime_vpc
      ecr_auto_create: false
      network_configuration:
        network_mode: VPC
        network_mode_config:
          security_groups:
          - sg-0affaea9ac4dc26b1
          subnets:
          - subnet-0b2fb367d6e823a79
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: deep_insight_runtime_vpc-c0LVReFA3o
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:057716757052:runtime/deep_insight_runtime_vpc-c0LVReFA3o
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-deep_insight_runtime_vpc-builder
      execution_role: arn:aws:iam::057716757052:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-360a3ba05a
      source_bucket: bedrock-agentcore-codebuild-sources-057716757052-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
