default_agent: deep_insight_runtime_vpc
agents:
  deep_insight_runtime_vpc:
    name: deep_insight_runtime_vpc
    entrypoint: /home/ubuntu/Self-Study-Generative-AI/lab/20_deep_insight/agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::057716757052:role/deep-insight-task-execution-role-prod
      execution_role_auto_create: false
      account: '057716757052'
      region: us-west-2
      ecr_repository: 057716757052.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-deep_insight_runtime_vpc
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: VPC
        network_mode_config:
          security_groups:
          - sg-030b461ae26b2d443
          subnets:
          - subnet-0260c5487ca1d6462
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: deep_insight_runtime_vpc-3Zm6bV7ZKV
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:057716757052:runtime/deep_insight_runtime_vpc-3Zm6bV7ZKV
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-deep_insight_runtime_vpc-builder
      execution_role: arn:aws:iam::057716757052:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-360a3ba05a
      source_bucket: bedrock-agentcore-codebuild-sources-057716757052-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
