AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Endpoints Stack - Bedrock AgentCore, ECR, CloudWatch Logs, S3'

Parameters:
  Environment:
    Type: String
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  VpcId:
    Type: String
    Description: VPC ID from Network Stack

  PrivateSubnet1Id:
    Type: String
    Description: Private Subnet 1 ID from Network Stack

  PrivateSubnet2Id:
    Type: String
    Description: Private Subnet 2 ID from Network Stack

  PrivateRouteTableId:
    Type: String
    Description: Private Route Table ID from Network Stack

  VPCEndpointSecurityGroupId:
    Type: String
    Description: VPC Endpoint Security Group ID from Security Groups Stack

Resources:
  # ============================================
  # Interface VPC Endpoints
  # ============================================

  # 1. Bedrock AgentCore Data Plane Endpoint
  BedrockAgentCoreDataPlaneEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.bedrock-agentcore'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-bedrock-data-vpce-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # 2. Bedrock AgentCore Gateway Endpoint
  BedrockAgentCoreGatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.bedrock-agentcore.gateway'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-bedrock-gateway-vpce-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # 3. ECR API Endpoint
  ECRAPIEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-ecr-api-vpce-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # 4. ECR Docker Endpoint
  ECRDockerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-ecr-dkr-vpce-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # 5. CloudWatch Logs Endpoint
  CloudWatchLogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-logs-vpce-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # 6. Bedrock Runtime Endpoint
  BedrockRuntimeEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.bedrock-runtime'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-bedrock-runtime-vpce-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ============================================
  # Gateway VPC Endpoints
  # ============================================

  # 7. S3 Gateway Endpoint
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTableId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-s3-vpce-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

# ============================================
# Outputs
# ============================================
Outputs:
  BedrockAgentCoreDataPlaneEndpointId:
    Description: Bedrock AgentCore Data Plane VPC Endpoint ID
    Value: !Ref BedrockAgentCoreDataPlaneEndpoint

  BedrockAgentCoreGatewayEndpointId:
    Description: Bedrock AgentCore Gateway VPC Endpoint ID
    Value: !Ref BedrockAgentCoreGatewayEndpoint

  ECRAPIEndpointId:
    Description: ECR API VPC Endpoint ID
    Value: !Ref ECRAPIEndpoint

  ECRDockerEndpointId:
    Description: ECR Docker VPC Endpoint ID
    Value: !Ref ECRDockerEndpoint

  CloudWatchLogsEndpointId:
    Description: CloudWatch Logs VPC Endpoint ID
    Value: !Ref CloudWatchLogsEndpoint

  BedrockRuntimeEndpointId:
    Description: Bedrock Runtime VPC Endpoint ID
    Value: !Ref BedrockRuntimeEndpoint

  S3GatewayEndpointId:
    Description: S3 Gateway VPC Endpoint ID
    Value: !Ref S3GatewayEndpoint
