AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Phase 2: Fargate Runtime Infrastructure
  Creates ECR Repository and ECS Task Definition for Deep Insight Fargate Runtime

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Default: deep-insight
    Description: Project name for resource naming

  # Phase 1 Outputs (from .env file)
  VpcId:
    Type: String
    Description: VPC ID from Phase 1

  PrivateSubnet1Id:
    Type: String
    Description: Private Subnet 1 ID from Phase 1

  PrivateSubnet2Id:
    Type: String
    Description: Private Subnet 2 ID from Phase 1

  FargateSecurityGroupId:
    Type: String
    Description: Fargate Security Group ID from Phase 1

  TaskExecutionRoleArn:
    Type: String
    Description: Task Execution Role ARN from Phase 1

  TaskRoleArn:
    Type: String
    Description: Task Role ARN from Phase 1

  # Deployment Stage Control
  DeployECS:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Set to 'false' for Stage 1 (ECR only), 'true' for Stage 2 (Full stack)

  # Docker Image
  DockerImageUri:
    Type: String
    Default: 'public.ecr.aws/docker/library/hello-world:latest'
    Description: Docker image URI in ECR (placeholder for Stage 1, real image for Stage 2)

  # ECS Configuration
  TaskCpu:
    Type: String
    Default: '2048'
    AllowedValues:
      - '256'
      - '512'
      - '1024'
      - '2048'
      - '4096'
    Description: Task CPU units (1024 = 1 vCPU)

  TaskMemory:
    Type: String
    Default: '4096'
    AllowedValues:
      - '512'
      - '1024'
      - '2048'
      - '4096'
      - '8192'
      - '16384'
      - '30720'
    Description: Task memory in MB

Conditions:
  ShouldDeployECS: !Equals [!Ref DeployECS, 'true']

Resources:
  # ============================================
  # ECR Repository
  # ============================================
  # Created first, then Docker image is pushed, then ECS resources are created
  ECRRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain  # Prevent accidental image deletion
    UpdateReplacePolicy: Retain
    Properties:
      RepositoryName: !Sub '${ProjectName}-fargate-runtime-${Environment}'
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-fargate-runtime-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ============================================
  # ECS Cluster
  # ============================================
  ECSCluster:
    Type: AWS::ECS::Cluster
    Condition: ShouldDeployECS
    Properties:
      ClusterName: !Sub '${ProjectName}-cluster-${Environment}'
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
          Base: 0
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-cluster-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ============================================
  # CloudWatch Log Group
  # ============================================
  LogGroup:
    Type: AWS::Logs::LogGroup
    Condition: ShouldDeployECS
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}-fargate-${Environment}'
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-fargate-logs-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ============================================
  # ECS Task Definition
  # ============================================
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Condition: ShouldDeployECS
    Properties:
      Family: !Sub '${ProjectName}-fargate-task-${Environment}'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: fargate-runtime
          Image: !Ref DockerImageUri
          Essential: true
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          Environment:
            - Name: ENV_NAME
              Value: !Ref Environment
            - Name: AWS_DEFAULT_REGION
              Value: !Ref AWS::Region
            - Name: PROJECT_NAME
              Value: !Ref ProjectName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: fargate
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:8080/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-fargate-task-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  ECRRepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepositoryUri'

  ECRRepositoryName:
    Description: ECR Repository Name
    Value: !Ref ECRRepository
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepositoryName'

  ECSClusterArn:
    Condition: ShouldDeployECS
    Description: ECS Cluster ARN
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ECSClusterArn'

  ECSClusterName:
    Condition: ShouldDeployECS
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${AWS::StackName}-ECSClusterName'

  TaskDefinitionArn:
    Condition: ShouldDeployECS
    Description: ECS Task Definition ARN
    Value: !Ref TaskDefinition
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefinitionArn'

  LogGroupName:
    Condition: ShouldDeployECS
    Description: CloudWatch Log Group Name
    Value: !Ref LogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupName'
